apiVersion: v1
kind: Service
metadata:
  name: reviewservice-service
spec:
  type: ClusterIP # Expone el servicio al exterior para manejar las rse√±as
  selector:
    app: reviewservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80